rollback 1.9 to v0.6.1

diff --git a/.github/workflows/update-clients.yml b/.github/workflows/update-clients.yml
--- a/.github/workflows/update-clients.yml
+++ b/.github/workflows/update-clients.yml
@@ -33,7 +33,6 @@ jobs:
             ./src/game/offline/main/EaglercraftX_1.8.html \
             ${{runner.temp}}/eaglerx/javascript/assets.epk \
             ${{runner.temp}}/eaglerx/javascript/classes.js \
-            ${{runner.temp}}/eaglerx/javascript/classes.js.map
           cd ${{runner.temp}}/eaglerx/
           chmod +x ./gradlew
           java -jar "desktopRuntime/CompileEPK.jar" "desktopRuntime/resources" "javascript/assets.epk"
@@ -43,30 +42,28 @@ jobs:
           cp -r ${{ runner.temp }}/eaglerx/javascript/lang/ ./src/game/web/main/1.8.8/lang/
           cp ${{ runner.temp }}/eaglerx/javascript/assets.epk ./src/game/web/main/1.8.8/assets.epk
           cp ${{ runner.temp }}/eaglerx/javascript/classes.js ./src/game/web/main/1.8.8/classes.js
-          cp ${{ runner.temp }}/eaglerx/javascript/classes.js.map ./src/game/web/main/1.8.8/classes.js.map
-      - name: Compile EaglercraftL 1.9
-        if: success() || failure()
-        run: |
-          git clone https://git.zelz.net/Eagler-Lambda/hoosiertransfer-mod.git ${{ runner.temp }}/eaglerl
-          rm -rf \
-            ./src/game/web/main/1.9.4/lang/ \
-            ./src/game/web/main/1.9.4/assets.epk \
-            ./src/game/web/main/1.9.4/classes.js \
-            ./src/game/web/main/1.9.4/classes.js.map \
-            ./src/game/offline/main/EaglercraftL_1.9.html \
-            ${{runner.temp}}/eaglerl/javascript/assets.epk \
-            ${{runner.temp}}/eaglerl/javascript/classes.js \
-            ${{runner.temp}}/eaglerl/javascript/classes.js.map
-          cd ${{runner.temp}}/eaglerl/
-          chmod +x ./gradlew
-          java -jar "resources/CompileEPK.jar" "resources/resources" "javascript/assets.epk"
-          ./gradlew generateJavascript
-          wget -O ${{ github.workspace }}/src/game/offline/main/EaglercraftL_1.9.html https://git.zelz.net/Eagler-Lambda/hoosiertransfer-mod/releases/download/latest/EaglercraftL_1.9_Offline_Signed_Client.html
-          cd ${{ github.workspace }}
-          cp -r ${{ runner.temp }}/eaglerl/javascript/lang/ ./src/game/web/main/1.9.4/lang/
-          cp ${{ runner.temp }}/eaglerl/javascript/assets.epk ./src/game/web/main/1.9.4/assets.epk
-          cp ${{ runner.temp }}/eaglerl/javascript/classes.js ./src/game/web/main/1.9.4/classes.js
-          cp ${{ runner.temp }}/eaglerl/javascript/classes.js.map ./src/game/web/main/1.9.4/classes.js.map
+      # FREEZE AT V0.6.1 UNTIL FURTHER NOTICE
+      #- name: Compile EaglercraftL 1.9
+      #  if: success() || failure()
+      #  run: |
+      #    git clone https://git.zelz.net/Eagler-Lambda/hoosiertransfer-mod.git ${{ runner.temp }}/eaglerl
+      #    rm -rf \
+      #      ./src/game/web/main/1.9.4/lang/ \
+      #      ./src/game/web/main/1.9.4/assets.epk \
+      #      ./src/game/web/main/1.9.4/classes.js \
+      #      ./src/game/web/main/1.9.4/classes.js.map \
+      #      ./src/game/offline/main/EaglercraftL_1.9.html \
+      #      ${{runner.temp}}/eaglerl/javascript/assets.epk \
+      #      ${{runner.temp}}/eaglerl/javascript/classes.js \
+      #    cd ${{runner.temp}}/eaglerl/
+      #    chmod +x ./gradlew
+      #    java -jar "resources/CompileEPK.jar" "resources/resources" "javascript/assets.epk"
+      #    ./gradlew generateJavascript
+      #    wget -O ${{ github.workspace }}/src/game/offline/main/EaglercraftL_1.9.html https://git.zelz.net/Eagler-Lambda/hoosiertransfer-mod/releases/download/latest/EaglercraftL_1.9_Offline_Signed_Client.html
+      #    cd ${{ github.workspace }}
+      #    cp -r ${{ runner.temp }}/eaglerl/javascript/lang/ ./src/game/web/main/1.9.4/lang/
+      #    cp ${{ runner.temp }}/eaglerl/javascript/assets.epk ./src/game/web/main/1.9.4/assets.epk
+      #    cp ${{ runner.temp }}/eaglerl/javascript/classes.js ./src/game/web/main/1.9.4/classes.js
       - name: Compile Shadow Client
         if: success() || failure()
         run: |
@@ -79,7 +76,6 @@ jobs:
             ./src/game/offline/clients/Shadow_Client.html \
             ${{runner.temp}}/shadow/javascript/assets.epk \
             ${{runner.temp}}/shadow/javascript/classes.js \
-            ${{runner.temp}}/shadow/javascript/classes.js.map
           cd ${{runner.temp}}/shadow/
           chmod +x ./gradlew
           java -jar "desktopRuntime/CompileEPK.jar" "desktopRuntime/resources" "javascript/assets.epk"
@@ -89,7 +85,6 @@ jobs:
           cp -r ${{ runner.temp }}/shadow/javascript/lang/ ./src/game/web/clients/shadow/lang/
           cp ${{ runner.temp }}/shadow/javascript/assets.epk ./src/game/web/clients/shadow/assets.epk
           cp ${{ runner.temp }}/shadow/javascript/classes.js ./src/game/web/clients/shadow/classes.js
-          cp ${{ runner.temp }}/shadow/javascript/classes.js.map ./src/game/web/clients/shadow/classes.js.map
           cp ${{ runner.temp }}/shadow/javascript/Shadow_Client_International.html ./src/game/offline/clients/Shadow_Client.html
       - name: Commit and push changes
         id: git-auto-commit-action
